from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from math import ceil
from pathlib import Path
from typing import Any

from gigastudy_api.domain.track_events import TrackPitchEvent
from gigastudy_api.services.engine.music_theory import (
    DEFAULT_TIME_SIGNATURE,
    NOTE_SEMITONES,
    TRACKS,
    note_from_pitch,
    quantize,
    quarter_beats_per_measure,
)
from gigastudy_api.services.engine.symbolic import ParsedSymbolicFile, ParsedTrack

try:
    import fitz
except ImportError:  # pragma: no cover - exercised when deployment misses PyMuPDF.
    fitz = None


class PdfVectorOmrError(ValueError):
    pass


NOTEHEAD_CHARS = {"\ue0a3", "\ue0a4", "\ue0a9", "\ue0db"}
ACCIDENTAL_OFFSETS = {"\ue260": -1, "\ue261": 0, "\ue262": 1}
SHARP_ORDER = ("F", "C", "G", "D", "A", "E", "B")
FLAT_ORDER = ("B", "E", "A", "D", "G", "C", "F")
OMR_GRID_BEATS = 0.25

LABEL_ALIASES: dict[str, int] = {
    "soprano": 1,
    "s": 1,
    "alto": 2,
    "a": 2,
    "tenor": 3,
    "t": 3,
    "baritone": 4,
    "br": 4,
    "bass": 5,
    "b": 5,
    "drumset": 6,
    "d. set": 6,
    "d.set": 6,
    "d": 6,
}

SLOT_PITCH_RANGES: dict[int, tuple[int, int]] = {
    1: (48, 95),
    2: (43, 88),
    3: (35, 80),
    4: (32, 75),
    5: (24, 72),
}


@dataclass
class _Glyph:
    char: str
    x: float
    y: float
    x0: float
    y0: float
    x1: float
    y1: float


@dataclass
class _StaffRow:
    page_index: int
    row_index: int
    top: float
    bottom: float
    center: float
    spacing: float
    x0: float
    x1: float
    slot_id: int | None = None
    label: str = ""


@dataclass
class _RawNote:
    slot_id: int
    page_index: int
    beat: float
    measure_index: int
    beat_in_measure: float
    pitch_midi: int
    confidence: float


def parse_born_digital_pdf_score(
    path: Path,
    *,
    bpm: int,
    time_signature_numerator: int = DEFAULT_TIME_SIGNATURE[0],
    time_signature_denominator: int = DEFAULT_TIME_SIGNATURE[1],
    max_slot_id: int = 5,
) -> ParsedSymbolicFile:
    """Extract reviewable pitch-event records from a born-digital score PDF.

    This is a practical fallback for PDFs generated by notation programs such as
    MuseScore. It reads vector staff lines, visible part labels, and SMuFL note
    glyph positions directly from the PDF. Scanned/image PDFs still need a real
    OMR engine such as Audiveris.
    """

    if fitz is None:
        raise PdfVectorOmrError("PyMuPDF is not installed.")
    if path.suffix.lower() != ".pdf":
        raise PdfVectorOmrError("Vector PDF extraction only supports PDF input.")

    try:
        document = fitz.open(path)
    except Exception as error:  # pragma: no cover - PyMuPDF exception type varies.
        raise PdfVectorOmrError(f"Could not open PDF: {error}") from error

    if document.page_count == 0:
        raise PdfVectorOmrError("PDF has no pages.")

    beats_per_measure = quarter_beats_per_measure(
        time_signature_numerator,
        time_signature_denominator,
    )
    raw_notes_by_slot: dict[int, list[_RawNote]] = defaultdict(list)
    next_measure_by_slot: dict[int, int] = defaultdict(lambda: 1)
    labelled_slots_seen: set[int] = set()
    staff_rows_by_slot: dict[int, int] = defaultdict(int)

    for page_index in range(document.page_count):
        page = document[page_index]
        staffs = _assign_staff_slots(page, _detect_staff_rows(page, page_index))
        glyphs = _extract_glyphs(page)
        for staff in staffs:
            if staff.slot_id is None or staff.slot_id > max_slot_id:
                continue
            labelled_slots_seen.add(staff.slot_id)
            staff_rows_by_slot[staff.slot_id] += 1
            row_notes, row_measure_count = _extract_notes_from_staff(
                page=page,
                staff=staff,
                staffs=staffs,
                glyphs=glyphs,
                next_measure=next_measure_by_slot[staff.slot_id],
                beats_per_measure=beats_per_measure,
            )
            raw_notes_by_slot[staff.slot_id].extend(row_notes)
            next_measure_by_slot[staff.slot_id] += max(1, row_measure_count)

    tracks: list[ParsedTrack] = []
    mapped_events: dict[int, list[TrackPitchEvent]] = {}
    for slot_id, raw_notes in sorted(raw_notes_by_slot.items()):
        notes = _finalize_track_notes(
            raw_notes,
            bpm=bpm,
            time_signature_numerator=time_signature_numerator,
            time_signature_denominator=time_signature_denominator,
            beats_per_measure=beats_per_measure,
        )
        if not notes:
            continue
        name = _track_name(slot_id)
        tracks.append(
            ParsedTrack(
                name=name,
                notes=notes,
                slot_id=slot_id,
                diagnostics=_build_vector_track_diagnostics(
                    slot_id=slot_id,
                    raw_notes=raw_notes,
                    notes=notes,
                    document_page_count=document.page_count,
                    detected_part_count=len(labelled_slots_seen),
                    staff_row_count=staff_rows_by_slot.get(slot_id, 0),
                    beats_per_measure=beats_per_measure,
                ),
            )
        )
        mapped_events[slot_id] = notes

    if not mapped_events:
        if labelled_slots_seen:
            raise PdfVectorOmrError("Part labels were found, but no score noteheads could be extracted.")
        raise PdfVectorOmrError("No labelled score staves could be extracted from the PDF.")

    return ParsedSymbolicFile(
        tracks=tracks,
        mapped_events=mapped_events,
        time_signature_numerator=time_signature_numerator,
        time_signature_denominator=time_signature_denominator,
        has_time_signature=False,
    )


def _detect_staff_rows(page: Any, page_index: int) -> list[_StaffRow]:
    horizontal_segments: list[tuple[float, float, float]] = []
    for drawing in page.get_drawings():
        for item in drawing.get("items", []):
            if item[0] != "l":
                continue
            point_a, point_b = item[1], item[2]
            x0, y0, x1, y1 = point_a.x, point_a.y, point_b.x, point_b.y
            if abs(y0 - y1) <= 0.25 and abs(x1 - x0) >= 70:
                horizontal_segments.append((min(x0, x1), max(x0, x1), y0))

    y_groups = _group_close_values((segment[2] for segment in horizontal_segments), tolerance=1.0)
    y_values = [sum(group) / len(group) for group in y_groups]
    staffs: list[_StaffRow] = []
    index = 0
    row_index = 0
    while index <= len(y_values) - 5:
        chunk = y_values[index : index + 5]
        diffs = [chunk[offset + 1] - chunk[offset] for offset in range(4)]
        average_spacing = sum(diffs) / len(diffs)
        if 2.0 <= average_spacing <= 8.0 and max(diffs) - min(diffs) <= 1.8:
            top, bottom = chunk[0], chunk[-1]
            x_values: list[float] = []
            for x0, x1, y in horizontal_segments:
                if top - 1 <= y <= bottom + 1:
                    x_values.extend([x0, x1])
            if x_values:
                x0, x1 = min(x_values), max(x_values)
            else:
                x0, x1 = 0.0, float(page.rect.width)
            staffs.append(
                _StaffRow(
                    page_index=page_index,
                    row_index=row_index,
                    top=top,
                    bottom=bottom,
                    center=(top + bottom) / 2,
                    spacing=average_spacing,
                    x0=x0,
                    x1=x1,
                )
            )
            row_index += 1
            index += 5
        else:
            index += 1
    return staffs


def _assign_staff_slots(page: Any, staffs: list[_StaffRow]) -> list[_StaffRow]:
    words = page.get_text("words")
    for staff in staffs:
        candidates: list[tuple[float, float, int, str]] = []
        for word in words:
            x0, y0, x1, y1, text, *_ = word
            if x1 > staff.x0 - 2:
                continue
            y_center = (y0 + y1) / 2
            if abs(y_center - staff.center) > max(18, staff.spacing * 4):
                continue
            slot_id = _slot_id_from_label(text)
            if slot_id is not None:
                candidates.append((abs(y_center - staff.center), x1, slot_id, text))
        if candidates:
            candidates.sort()
            _, _, staff.slot_id, staff.label = candidates[0]
    return staffs


def _extract_notes_from_staff(
    *,
    page: Any,
    staff: _StaffRow,
    staffs: list[_StaffRow],
    glyphs: list[_Glyph],
    next_measure: int,
    beats_per_measure: float,
) -> tuple[list[_RawNote], int]:
    intervals = _measure_intervals(page, staff, staffs, glyphs)
    key_alterations = _key_signature_alterations(staff, glyphs, intervals[0][0])
    raw_notes: list[_RawNote] = []
    seen_keys: set[tuple[int, int, int]] = set()

    for glyph in sorted((glyph for glyph in glyphs if glyph.char in NOTEHEAD_CHARS), key=lambda item: item.x):
        if not staff.x0 - 5 <= glyph.x <= staff.x1 + 5:
            continue
        if abs(glyph.y - staff.center) > staff.spacing * 8:
            continue
        nearest_staff = min(staffs, key=lambda candidate: abs(glyph.y - candidate.center))
        if nearest_staff is not staff:
            continue

        pitch_midi, letter = _pitch_from_staff_y(staff, glyph.y)
        explicit_accidental = _explicit_accidental_for_note(glyph, glyphs, staff)
        if explicit_accidental is None:
            pitch_midi += key_alterations.get(letter, 0)
        else:
            naturalized_midi = _natural_midi_for_letter(pitch_midi, letter)
            pitch_midi = naturalized_midi + explicit_accidental

        if not _pitch_in_slot_range(staff.slot_id, pitch_midi):
            continue

        measure_offset, beat_in_measure = _measure_position_for_x(
            glyph.x,
            intervals,
            beats_per_measure,
        )
        measure_index = next_measure + measure_offset
        absolute_beat = (measure_index - 1) * beats_per_measure + beat_in_measure
        dedupe_key = (measure_index, round(beat_in_measure * 4), pitch_midi)
        if dedupe_key in seen_keys:
            continue
        seen_keys.add(dedupe_key)
        raw_notes.append(
            _RawNote(
                slot_id=staff.slot_id or 1,
                page_index=staff.page_index,
                beat=absolute_beat,
                measure_index=measure_index,
                beat_in_measure=beat_in_measure,
                pitch_midi=pitch_midi,
                confidence=0.62,
            )
        )

    return raw_notes, len(intervals)


def _measure_intervals(
    page: Any,
    staff: _StaffRow,
    staffs: list[_StaffRow],
    glyphs: list[_Glyph],
) -> list[tuple[float, float]]:
    verticals = _staff_vertical_barlines(page, staff, staffs)
    note_xs = [
        glyph.x
        for glyph in glyphs
        if glyph.char in NOTEHEAD_CHARS
        and staff.x0 - 5 <= glyph.x <= staff.x1 + 5
        and abs(glyph.y - staff.center) <= staff.spacing * 8
    ]
    if not verticals:
        return [(staff.x0, staff.x1)]

    intervals: list[tuple[float, float]] = []
    first_boundary = verticals[0]
    first_notes = [x for x in note_xs if staff.x0 <= x <= first_boundary + 2]
    if first_boundary - staff.x0 > 20:
        if first_notes:
            first_left = max(staff.x0, min(first_notes) - staff.spacing * 3)
        else:
            first_left = staff.x0
        if first_boundary - first_left > 8:
            intervals.append((first_left, first_boundary))
    else:
        first_left = staff.x0
        if len(verticals) == 1 and staff.x1 - first_left > 8:
            intervals.append((first_left, staff.x1))

    for left, right in zip(verticals, verticals[1:]):
        if right - left > 8:
            intervals.append((left, right))
    if staff.x1 - verticals[-1] > 18:
        intervals.append((verticals[-1], staff.x1))

    if not intervals:
        return [(staff.x0, staff.x1)]
    return intervals


def _staff_vertical_barlines(page: Any, staff: _StaffRow, staffs: list[_StaffRow]) -> list[float]:
    peers = _system_peers(staff, staffs)
    labelled_peers = [peer for peer in peers if peer.slot_id is not None]
    threshold = min(3, max(2, len(labelled_peers) // 2 + 1))
    values_by_peer: list[tuple[int, float]] = []
    for peer in peers:
        for value in _staff_vertical_candidates(page, peer):
            values_by_peer.append((peer.row_index, value))

    groups = _group_close_values((value for _, value in values_by_peer), tolerance=2.0)
    common_values: list[float] = []
    for group in groups:
        peer_ids = {
            peer_id
            for peer_id, value in values_by_peer
            if min(group) - 0.1 <= value <= max(group) + 0.1
        }
        if len(peer_ids) >= threshold:
            common_values.append(sum(group) / len(group))
    return [value for value in common_values if staff.x0 - 3 <= value <= staff.x1 + 3]


def _staff_vertical_candidates(page: Any, staff: _StaffRow) -> list[float]:
    values: list[float] = []
    for drawing in page.get_drawings():
        for item in drawing.get("items", []):
            if item[0] != "l":
                continue
            point_a, point_b = item[1], item[2]
            x0, y0, x1, y1 = point_a.x, point_a.y, point_b.x, point_b.y
            if abs(x0 - x1) > 0.4:
                continue
            y_min, y_max = min(y0, y1), max(y0, y1)
            if y_max < staff.top - 1 or y_min > staff.bottom + 1:
                continue
            if abs(y_min - staff.top) > staff.spacing * 0.7:
                continue
            if abs(y_max - staff.bottom) > staff.spacing * 0.7:
                continue
            if staff.x0 - 3 <= x0 <= staff.x1 + 3:
                values.append(x0)
    return [sum(group) / len(group) for group in _group_close_values(values, tolerance=2.0)]


def _system_peers(staff: _StaffRow, staffs: list[_StaffRow]) -> list[_StaffRow]:
    try:
        current_index = staffs.index(staff)
    except ValueError:
        return [staff]

    if staff.slot_id == 1:
        start_index = current_index
    else:
        start_index = 0
        for index in range(current_index, -1, -1):
            if staffs[index].slot_id == 1:
                start_index = index
                break
    end_index = len(staffs)
    for index in range(current_index + 1, len(staffs)):
        if staffs[index].slot_id == 1:
            end_index = index
            break
    return staffs[start_index:end_index]


def _measure_position_for_x(
    x: float,
    intervals: list[tuple[float, float]],
    beats_per_measure: float,
) -> tuple[int, float]:
    interval_index = 0
    for candidate_index, (left, right) in enumerate(intervals):
        if left - 1 <= x <= right + 1:
            interval_index = candidate_index
            break
        if x > right:
            interval_index = candidate_index
    left, right = intervals[interval_index]
    fraction = (x - left) / max(1.0, right - left)
    beat_in_measure = quantize(1 + fraction * beats_per_measure, OMR_GRID_BEATS)
    latest_onset = max(1.0, beats_per_measure + 1 - OMR_GRID_BEATS)
    beat_in_measure = max(1.0, min(latest_onset, beat_in_measure))
    return interval_index, beat_in_measure


def _finalize_track_notes(
    raw_notes: list[_RawNote],
    *,
    bpm: int,
    time_signature_numerator: int,
    time_signature_denominator: int,
    beats_per_measure: float,
) -> list[TrackPitchEvent]:
    raw_notes = sorted(raw_notes, key=lambda note: (note.beat, note.pitch_midi))
    deduped: list[_RawNote] = []
    for raw_note in raw_notes:
        if deduped and abs(raw_note.beat - deduped[-1].beat) <= 0.01 and raw_note.pitch_midi == deduped[-1].pitch_midi:
            continue
        deduped.append(raw_note)

    notes: list[TrackPitchEvent] = []
    for index, raw_note in enumerate(deduped):
        next_beat = deduped[index + 1].beat if index + 1 < len(deduped) else raw_note.beat + 1
        measure_end_beat = raw_note.measure_index * beats_per_measure + 1
        measure_remaining = max(OMR_GRID_BEATS, measure_end_beat - raw_note.beat)
        duration_beats = quantize(next_beat - raw_note.beat, OMR_GRID_BEATS)
        if duration_beats <= 0:
            duration_beats = OMR_GRID_BEATS
        duration_beats = min(duration_beats, measure_remaining, beats_per_measure)
        notes.append(
            note_from_pitch(
                beat=raw_note.beat,
                duration_beats=duration_beats,
                bpm=bpm,
                source="omr",
                extraction_method="pdf_vector_omr_v0",
                time_signature_numerator=time_signature_numerator,
                time_signature_denominator=time_signature_denominator,
                pitch_midi=raw_note.pitch_midi,
                confidence=raw_note.confidence,
                measure_index=raw_note.measure_index,
                beat_in_measure=raw_note.beat_in_measure,
            )
        )
    return notes


def _build_vector_track_diagnostics(
    *,
    slot_id: int,
    raw_notes: list[_RawNote],
    notes: list[TrackPitchEvent],
    document_page_count: int,
    detected_part_count: int,
    staff_row_count: int,
    beats_per_measure: float,
) -> dict[str, Any]:
    pitched_notes = [
        note
        for note in notes
        if not note.is_rest and note.pitch_midi is not None
    ]
    measure_indices = {
        note.measure_index
        for note in notes
        if note.measure_index is not None
    }
    page_indices = {raw_note.page_index for raw_note in raw_notes}
    range_fit_ratio = _range_fit_ratio(slot_id, pitched_notes)
    timing_grid_ratio = _timing_grid_ratio(notes)
    avg_note_confidence = (
        sum(note.confidence for note in notes) / len(notes)
        if notes
        else 0
    )
    duration_beats = 0.0
    if notes:
        duration_beats = max(note.beat + max(note.duration_beats, 0.25) - 1 for note in notes)
    measure_count = len(measure_indices) or max(1, ceil(duration_beats / max(0.25, beats_per_measure)))
    return {
        "engine": "pdf_vector_omr_v0",
        "document_page_count": document_page_count,
        "candidate_page_count": len(page_indices),
        "detected_part_count": detected_part_count,
        "source_row_count": staff_row_count,
        "event_count": len(notes),
        "pitched_event_count": len(pitched_notes),
        "measure_count": measure_count,
        "avg_note_confidence": round(avg_note_confidence, 3),
        "range_fit_ratio": round(range_fit_ratio, 3),
        "timing_grid_ratio": round(timing_grid_ratio, 3),
        "density_events_per_measure": round(len(notes) / max(1, measure_count), 2),
        "review_hint": _vector_review_hint(
            event_count=len(notes),
            range_fit_ratio=range_fit_ratio,
            timing_grid_ratio=timing_grid_ratio,
            detected_part_count=detected_part_count,
        ),
    }


def _range_fit_ratio(slot_id: int, notes: list[TrackPitchEvent]) -> float:
    if not notes:
        return 0
    low, high = SLOT_PITCH_RANGES.get(slot_id, (0, 127))
    in_range = [
        note
        for note in notes
        if note.pitch_midi is not None and low <= note.pitch_midi <= high
    ]
    return len(in_range) / len(notes)


def _timing_grid_ratio(notes: list[TrackPitchEvent]) -> float:
    if not notes:
        return 0
    aligned = 0
    for note in notes:
        beat_aligned = abs(note.beat * 4 - round(note.beat * 4)) <= 0.03
        duration_aligned = abs(note.duration_beats * 4 - round(note.duration_beats * 4)) <= 0.03
        if beat_aligned and duration_aligned:
            aligned += 1
    return aligned / len(notes)


def _vector_review_hint(
    *,
    event_count: int,
    range_fit_ratio: float,
    timing_grid_ratio: float,
    detected_part_count: int,
) -> str:
    if event_count < 4:
        return "few_events"
    if range_fit_ratio < 0.85:
        return "range_outliers"
    if timing_grid_ratio < 0.82:
        return "rhythm_grid_review"
    if detected_part_count < 4:
        return "partial_document_review"
    return "review_accidentals_and_rhythm"


def _extract_glyphs(page: Any) -> list[_Glyph]:
    glyphs: list[_Glyph] = []
    raw = page.get_text("rawdict")
    for block in raw.get("blocks", []):
        for line in block.get("lines", []):
            for span in line.get("spans", []):
                for char in span.get("chars", []):
                    value = char.get("c", "")
                    bbox = char.get("bbox")
                    if not bbox:
                        continue
                    x0, y0, x1, y1 = bbox
                    glyphs.append(
                        _Glyph(
                            char=value,
                            x=(x0 + x1) / 2,
                            y=(y0 + y1) / 2,
                            x0=x0,
                            y0=y0,
                            x1=x1,
                            y1=y1,
                        )
                    )
    return glyphs


def _key_signature_alterations(
    staff: _StaffRow,
    glyphs: list[_Glyph],
    first_measure_left: float,
) -> dict[str, int]:
    accidentals = [
        glyph
        for glyph in glyphs
        if glyph.char in ACCIDENTAL_OFFSETS
        and staff.x0 <= glyph.x <= max(first_measure_left, staff.x0 + staff.spacing * 8)
        and abs(glyph.y - staff.center) <= staff.spacing * 5
    ]
    groups = _group_close_values((glyph.x for glyph in accidentals), tolerance=2.0)
    if not groups:
        return {}

    offsets_by_group: list[int] = []
    for group in groups:
        group_chars = [
            glyph.char
            for glyph in accidentals
            if min(group) - 0.1 <= glyph.x <= max(group) + 0.1
        ]
        if not group_chars:
            continue
        offsets = [ACCIDENTAL_OFFSETS[char] for char in group_chars if char in ACCIDENTAL_OFFSETS]
        if offsets:
            offsets_by_group.append(max(set(offsets), key=offsets.count))

    sharp_count = sum(1 for offset in offsets_by_group if offset == 1)
    flat_count = sum(1 for offset in offsets_by_group if offset == -1)
    if sharp_count >= flat_count and sharp_count > 0:
        return {letter: 1 for letter in SHARP_ORDER[: min(sharp_count, len(SHARP_ORDER))]}
    if flat_count > 0:
        return {letter: -1 for letter in FLAT_ORDER[: min(flat_count, len(FLAT_ORDER))]}
    return {}


def _explicit_accidental_for_note(glyph: _Glyph, glyphs: list[_Glyph], staff: _StaffRow) -> int | None:
    candidates = [
        accidental
        for accidental in glyphs
        if accidental.char in ACCIDENTAL_OFFSETS
        and 1 <= glyph.x - accidental.x <= staff.spacing * 5
        and abs(glyph.y - accidental.y) <= staff.spacing * 1.8
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda item: glyph.x - item.x)
    return ACCIDENTAL_OFFSETS[candidates[0].char]


def _pitch_from_staff_y(staff: _StaffRow, y: float) -> tuple[int, str]:
    if staff.slot_id == 5:
        bottom_letter = "G"
        bottom_octave = 2
    else:
        bottom_letter = "E"
        bottom_octave = 4
        if staff.slot_id in {3, 4}:
            bottom_octave -= 1

    diatonic_step = round((staff.bottom - y) / (staff.spacing / 2))
    bottom_index = _diatonic_index(bottom_letter, bottom_octave)
    target_index = bottom_index + diatonic_step
    octave, letter_index = divmod(target_index, 7)
    letter = ("C", "D", "E", "F", "G", "A", "B")[letter_index]
    midi = (octave + 1) * 12 + NOTE_SEMITONES[letter]
    return midi, letter


def _natural_midi_for_letter(midi: int, letter: str) -> int:
    octave = midi // 12 - 1
    base = (octave + 1) * 12 + NOTE_SEMITONES[letter]
    candidates = [base - 12, base, base + 12]
    return min(candidates, key=lambda candidate: abs(candidate - midi))


def _diatonic_index(letter: str, octave: int) -> int:
    return octave * 7 + ("C", "D", "E", "F", "G", "A", "B").index(letter)


def _pitch_in_slot_range(slot_id: int | None, pitch_midi: int) -> bool:
    if slot_id is None:
        return False
    low, high = SLOT_PITCH_RANGES.get(slot_id, (0, 127))
    return low <= pitch_midi <= high


def _slot_id_from_label(text: str) -> int | None:
    normalized = re.sub(r"\s+", " ", text.strip().lower())
    return LABEL_ALIASES.get(normalized)


def _group_close_values(values: Any, *, tolerance: float) -> list[list[float]]:
    groups: list[list[float]] = []
    for value in sorted(float(candidate) for candidate in values):
        if not groups or abs(value - groups[-1][-1]) > tolerance:
            groups.append([value])
        else:
            groups[-1].append(value)
    return groups


def _track_name(slot_id: int) -> str:
    for candidate_slot_id, name in TRACKS:
        if candidate_slot_id == slot_id:
            return name
    return f"Track {slot_id}"
