from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from math import ceil
from pathlib import Path
from typing import Any

from gigastudy_api.domain.track_events import TrackPitchEvent
from gigastudy_api.services.engine.music_theory import (
    DEFAULT_TIME_SIGNATURE,
    PITCH_CLASS_SEMITONES,
    TRACKS,
    event_from_pitch,
    quantize,
    quarter_beats_per_measure,
)
from gigastudy_api.services.engine.symbolic import ParsedSymbolicFile, ParsedTrack

try:
    import fitz
except ImportError:  # pragma: no cover - exercised when deployment misses PyMuPDF.
    fitz = None


class PdfVectorDocumentError(ValueError):
    pass


PITCH_EVENT_GLYPH_CHARS = {"\ue0a3", "\ue0a4", "\ue0a9", "\ue0db"}
ACCIDENTAL_OFFSETS = {"\ue260": -1, "\ue261": 0, "\ue262": 1}
SHARP_ORDER = ("F", "C", "G", "D", "A", "E", "B")
FLAT_ORDER = ("B", "E", "A", "D", "G", "C", "F")
DOCUMENT_GRID_BEATS = 0.25

LABEL_ALIASES: dict[str, int] = {
    "soprano": 1,
    "s": 1,
    "alto": 2,
    "a": 2,
    "tenor": 3,
    "t": 3,
    "baritone": 4,
    "bariton": 4,
    "bari": 4,
    "br": 4,
    "bass": 5,
    "b": 5,
    "drumset": 6,
    "d. set": 6,
    "d.set": 6,
    "d": 6,
    "소프라노": 1,
    "알토": 2,
    "테너": 3,
    "바리톤": 4,
    "베이스": 5,
    "퍼커션": 6,
}

SLOT_PITCH_RANGES: dict[int, tuple[int, int]] = {
    1: (48, 95),
    2: (43, 88),
    3: (35, 80),
    4: (32, 75),
    5: (24, 72),
}


@dataclass
class _Glyph:
    char: str
    x: float
    y: float
    x0: float
    y0: float
    x1: float
    y1: float


@dataclass
class _DocumentRow:
    page_index: int
    row_index: int
    top: float
    bottom: float
    center: float
    spacing: float
    x0: float
    x1: float
    slot_id: int | None = None
    label: str = ""


@dataclass
class _RawDocumentEvent:
    slot_id: int
    page_index: int
    beat: float
    measure_index: int
    beat_in_measure: float
    pitch_midi: int
    confidence: float


def parse_born_digital_pdf_document(
    path: Path,
    *,
    bpm: int,
    time_signature_numerator: int = DEFAULT_TIME_SIGNATURE[0],
    time_signature_denominator: int = DEFAULT_TIME_SIGNATURE[1],
    max_slot_id: int = 5,
) -> ParsedSymbolicFile:
    """Extract reviewable pitch-event records from a born-digital document PDF.

    This is a practical fallback for PDFs generated by symbolic music editors.
    It reads vector source rows, visible part labels, and SMuFL pitch-event glyph
    positions directly from the PDF. Scanned/image PDFs still need a real
    document extraction engine such as Audiveris.
    """

    if fitz is None:
        raise PdfVectorDocumentError("PyMuPDF is not installed.")
    if path.suffix.lower() != ".pdf":
        raise PdfVectorDocumentError("Vector PDF extraction only supports PDF input.")

    try:
        document = fitz.open(path)
    except Exception as error:  # pragma: no cover - PyMuPDF exception type varies.
        raise PdfVectorDocumentError(f"Could not open PDF: {error}") from error

    if document.page_count == 0:
        raise PdfVectorDocumentError("PDF has no pages.")

    beats_per_measure = quarter_beats_per_measure(
        time_signature_numerator,
        time_signature_denominator,
    )
    raw_events_by_slot: dict[int, list[_RawDocumentEvent]] = defaultdict(list)
    next_measure_by_slot: dict[int, int] = defaultdict(lambda: 1)
    labelled_slots_seen: set[int] = set()
    source_rows_by_slot: dict[int, int] = defaultdict(int)

    for page_index in range(document.page_count):
        page = document[page_index]
        rows = _assign_document_slots(page, _detect_document_rows(page, page_index))
        glyphs = _extract_glyphs(page)
        for row in rows:
            if row.slot_id is None or row.slot_id > max_slot_id:
                continue
            labelled_slots_seen.add(row.slot_id)
            source_rows_by_slot[row.slot_id] += 1
            row_events, row_measure_count = _extract_events_from_row(
                page=page,
                row=row,
                rows=rows,
                glyphs=glyphs,
                next_measure=next_measure_by_slot[row.slot_id],
                beats_per_measure=beats_per_measure,
            )
            raw_events_by_slot[row.slot_id].extend(row_events)
            next_measure_by_slot[row.slot_id] += max(1, row_measure_count)

    tracks: list[ParsedTrack] = []
    mapped_events: dict[int, list[TrackPitchEvent]] = {}
    for slot_id, raw_events in sorted(raw_events_by_slot.items()):
        events = _finalize_track_events(
            raw_events,
            bpm=bpm,
            time_signature_numerator=time_signature_numerator,
            time_signature_denominator=time_signature_denominator,
            beats_per_measure=beats_per_measure,
        )
        if not events:
            continue
        name = _track_name(slot_id)
        tracks.append(
            ParsedTrack(
                name=name,
                events=events,
                slot_id=slot_id,
                diagnostics=_build_vector_track_diagnostics(
                    slot_id=slot_id,
                    raw_events=raw_events,
                    events=events,
                    document_page_count=document.page_count,
                    detected_part_count=len(labelled_slots_seen),
                    source_row_count=source_rows_by_slot.get(slot_id, 0),
                    beats_per_measure=beats_per_measure,
                ),
            )
        )
        mapped_events[slot_id] = events

    if not mapped_events:
        if labelled_slots_seen:
            raise PdfVectorDocumentError("Part labels were found, but no pitch-event glyphs could be extracted.")
        raise PdfVectorDocumentError("No labelled document rows could be extracted from the PDF.")

    return ParsedSymbolicFile(
        tracks=tracks,
        mapped_events=mapped_events,
        time_signature_numerator=time_signature_numerator,
        time_signature_denominator=time_signature_denominator,
        has_time_signature=False,
    )


def _detect_document_rows(page: Any, page_index: int) -> list[_DocumentRow]:
    horizontal_segments: list[tuple[float, float, float]] = []
    for drawing in page.get_drawings():
        for item in drawing.get("items", []):
            if item[0] != "l":
                continue
            point_a, point_b = item[1], item[2]
            x0, y0, x1, y1 = point_a.x, point_a.y, point_b.x, point_b.y
            if abs(y0 - y1) <= 0.25 and abs(x1 - x0) >= 70:
                horizontal_segments.append((min(x0, x1), max(x0, x1), y0))

    y_groups = _group_close_values((segment[2] for segment in horizontal_segments), tolerance=1.0)
    y_values = [sum(group) / len(group) for group in y_groups]
    rows: list[_DocumentRow] = []
    index = 0
    row_index = 0
    while index <= len(y_values) - 5:
        chunk = y_values[index : index + 5]
        diffs = [chunk[offset + 1] - chunk[offset] for offset in range(4)]
        average_spacing = sum(diffs) / len(diffs)
        if 2.0 <= average_spacing <= 8.0 and max(diffs) - min(diffs) <= 1.8:
            top, bottom = chunk[0], chunk[-1]
            x_values: list[float] = []
            for x0, x1, y in horizontal_segments:
                if top - 1 <= y <= bottom + 1:
                    x_values.extend([x0, x1])
            if x_values:
                x0, x1 = min(x_values), max(x_values)
            else:
                x0, x1 = 0.0, float(page.rect.width)
            rows.append(
                _DocumentRow(
                    page_index=page_index,
                    row_index=row_index,
                    top=top,
                    bottom=bottom,
                    center=(top + bottom) / 2,
                    spacing=average_spacing,
                    x0=x0,
                    x1=x1,
                )
            )
            row_index += 1
            index += 5
        else:
            index += 1
    return rows


def _assign_document_slots(page: Any, rows: list[_DocumentRow]) -> list[_DocumentRow]:
    words = page.get_text("words")
    for row in rows:
        candidates: list[tuple[float, float, int, str]] = []
        for word in words:
            x0, y0, x1, y1, text, *_ = word
            if x1 > row.x0 - 2:
                continue
            y_center = (y0 + y1) / 2
            if abs(y_center - row.center) > max(18, row.spacing * 4):
                continue
            slot_id = _slot_id_from_label(text)
            if slot_id is not None:
                candidates.append((abs(y_center - row.center), x1, slot_id, text))
        if candidates:
            candidates.sort()
            _, _, row.slot_id, row.label = candidates[0]
    return _assign_unlabelled_document_slots(rows)


def _assign_unlabelled_document_slots(rows: list[_DocumentRow]) -> list[_DocumentRow]:
    if not rows:
        return rows
    systems = _group_rows_into_systems(rows)
    for system in systems:
        missing_rows = [row for row in system if row.slot_id is None]
        if not missing_rows:
            continue
        if any(row.slot_id is not None for row in system):
            used_slots = {row.slot_id for row in system if row.slot_id is not None}
            available_slots = [slot_id for slot_id in _slots_for_staff_count(len(system)) if slot_id not in used_slots]
        else:
            available_slots = _slots_for_staff_count(len(system))
        for row, slot_id in zip(missing_rows, available_slots):
            row.slot_id = slot_id
            row.label = f"inferred-{slot_id}"
    return rows


def _group_rows_into_systems(rows: list[_DocumentRow]) -> list[list[_DocumentRow]]:
    sorted_rows = sorted(rows, key=lambda row: (row.page_index, row.center))
    systems: list[list[_DocumentRow]] = []
    current: list[_DocumentRow] = []
    previous: _DocumentRow | None = None
    for row in sorted_rows:
        gap = row.top - previous.bottom if previous is not None and previous.page_index == row.page_index else None
        if previous is None or previous.page_index != row.page_index or (gap is not None and gap > max(22, previous.spacing * 6)):
            if current:
                systems.append(current)
            current = [row]
        else:
            current.append(row)
        previous = row
    if current:
        systems.append(current)
    return systems


def _slots_for_staff_count(count: int) -> list[int]:
    if count <= 1:
        return [1]
    if count == 2:
        return [1, 5]
    if count == 3:
        return [1, 3, 5]
    if count == 4:
        return [1, 2, 3, 5]
    return [1, 2, 3, 4, 5]


def _extract_events_from_row(
    *,
    page: Any,
    row: _DocumentRow,
    rows: list[_DocumentRow],
    glyphs: list[_Glyph],
    next_measure: int,
    beats_per_measure: float,
) -> tuple[list[_RawDocumentEvent], int]:
    intervals = _measure_intervals(page, row, rows, glyphs)
    key_alterations = _key_signature_alterations(row, glyphs, intervals[0][0])
    raw_events: list[_RawDocumentEvent] = []
    seen_keys: set[tuple[int, int, int]] = set()

    for glyph in sorted((glyph for glyph in glyphs if glyph.char in PITCH_EVENT_GLYPH_CHARS), key=lambda item: item.x):
        if not row.x0 - 5 <= glyph.x <= row.x1 + 5:
            continue
        if abs(glyph.y - row.center) > row.spacing * 8:
            continue
        nearest_row = min(rows, key=lambda candidate: abs(glyph.y - candidate.center))
        if nearest_row is not row:
            continue

        pitch_midi, letter = _pitch_from_row_y(row, glyph.y)
        explicit_accidental = _explicit_accidental_for_event(glyph, glyphs, row)
        if explicit_accidental is None:
            pitch_midi += key_alterations.get(letter, 0)
        else:
            naturalized_midi = _natural_midi_for_letter(pitch_midi, letter)
            pitch_midi = naturalized_midi + explicit_accidental

        if not _pitch_in_slot_range(row.slot_id, pitch_midi):
            continue

        measure_offset, beat_in_measure = _measure_position_for_x(
            glyph.x,
            intervals,
            beats_per_measure,
        )
        measure_index = next_measure + measure_offset
        absolute_beat = (measure_index - 1) * beats_per_measure + beat_in_measure
        dedupe_key = (measure_index, round(beat_in_measure * 4), pitch_midi)
        if dedupe_key in seen_keys:
            continue
        seen_keys.add(dedupe_key)
        raw_events.append(
            _RawDocumentEvent(
                slot_id=row.slot_id or 1,
                page_index=row.page_index,
                beat=absolute_beat,
                measure_index=measure_index,
                beat_in_measure=beat_in_measure,
                pitch_midi=pitch_midi,
                confidence=0.62,
            )
        )

    return raw_events, len(intervals)


def _measure_intervals(
    page: Any,
    row: _DocumentRow,
    rows: list[_DocumentRow],
    glyphs: list[_Glyph],
) -> list[tuple[float, float]]:
    verticals = _row_vertical_barlines(page, row, rows)
    event_xs = [
        glyph.x
        for glyph in glyphs
        if glyph.char in PITCH_EVENT_GLYPH_CHARS
        and row.x0 - 5 <= glyph.x <= row.x1 + 5
        and abs(glyph.y - row.center) <= row.spacing * 8
    ]
    if not verticals:
        return [(row.x0, row.x1)]

    intervals: list[tuple[float, float]] = []
    first_boundary = verticals[0]
    first_events = [x for x in event_xs if row.x0 <= x <= first_boundary + 2]
    if first_boundary - row.x0 > 20:
        if first_events:
            first_left = max(row.x0, min(first_events) - row.spacing * 3)
        else:
            first_left = row.x0
        if first_boundary - first_left > 8:
            intervals.append((first_left, first_boundary))
    else:
        first_left = row.x0
        if len(verticals) == 1 and row.x1 - first_left > 8:
            intervals.append((first_left, row.x1))

    for left, right in zip(verticals, verticals[1:]):
        if right - left > 8:
            intervals.append((left, right))
    if row.x1 - verticals[-1] > 18:
        intervals.append((verticals[-1], row.x1))

    if not intervals:
        return [(row.x0, row.x1)]
    return intervals


def _row_vertical_barlines(page: Any, row: _DocumentRow, rows: list[_DocumentRow]) -> list[float]:
    peers = _system_peers(row, rows)
    labelled_peers = [peer for peer in peers if peer.slot_id is not None]
    threshold = min(3, max(2, len(labelled_peers) // 2 + 1))
    values_by_peer: list[tuple[int, float]] = []
    for peer in peers:
        for value in _row_vertical_candidates(page, peer):
            values_by_peer.append((peer.row_index, value))

    groups = _group_close_values((value for _, value in values_by_peer), tolerance=2.0)
    common_values: list[float] = []
    for group in groups:
        peer_ids = {
            peer_id
            for peer_id, value in values_by_peer
            if min(group) - 0.1 <= value <= max(group) + 0.1
        }
        if len(peer_ids) >= threshold:
            common_values.append(sum(group) / len(group))
    return [value for value in common_values if row.x0 - 3 <= value <= row.x1 + 3]


def _row_vertical_candidates(page: Any, row: _DocumentRow) -> list[float]:
    values: list[float] = []
    for drawing in page.get_drawings():
        for item in drawing.get("items", []):
            if item[0] != "l":
                continue
            point_a, point_b = item[1], item[2]
            x0, y0, x1, y1 = point_a.x, point_a.y, point_b.x, point_b.y
            if abs(x0 - x1) > 0.4:
                continue
            y_min, y_max = min(y0, y1), max(y0, y1)
            if y_max < row.top - 1 or y_min > row.bottom + 1:
                continue
            if abs(y_min - row.top) > row.spacing * 0.7:
                continue
            if abs(y_max - row.bottom) > row.spacing * 0.7:
                continue
            if row.x0 - 3 <= x0 <= row.x1 + 3:
                values.append(x0)
    return [sum(group) / len(group) for group in _group_close_values(values, tolerance=2.0)]


def _system_peers(row: _DocumentRow, rows: list[_DocumentRow]) -> list[_DocumentRow]:
    try:
        current_index = rows.index(row)
    except ValueError:
        return [row]

    if row.slot_id == 1:
        start_index = current_index
    else:
        start_index = 0
        for index in range(current_index, -1, -1):
            if rows[index].slot_id == 1:
                start_index = index
                break
    end_index = len(rows)
    for index in range(current_index + 1, len(rows)):
        if rows[index].slot_id == 1:
            end_index = index
            break
    return rows[start_index:end_index]


def _measure_position_for_x(
    x: float,
    intervals: list[tuple[float, float]],
    beats_per_measure: float,
) -> tuple[int, float]:
    interval_index = 0
    for candidate_index, (left, right) in enumerate(intervals):
        if left - 1 <= x <= right + 1:
            interval_index = candidate_index
            break
        if x > right:
            interval_index = candidate_index
    left, right = intervals[interval_index]
    fraction = (x - left) / max(1.0, right - left)
    beat_in_measure = quantize(1 + fraction * beats_per_measure, DOCUMENT_GRID_BEATS)
    latest_onset = max(1.0, beats_per_measure + 1 - DOCUMENT_GRID_BEATS)
    beat_in_measure = max(1.0, min(latest_onset, beat_in_measure))
    return interval_index, beat_in_measure


def _finalize_track_events(
    raw_events: list[_RawDocumentEvent],
    *,
    bpm: int,
    time_signature_numerator: int,
    time_signature_denominator: int,
    beats_per_measure: float,
) -> list[TrackPitchEvent]:
    raw_events = sorted(raw_events, key=lambda event: (event.beat, event.pitch_midi))
    deduped: list[_RawDocumentEvent] = []
    for raw_event in raw_events:
        if (
            deduped
            and abs(raw_event.beat - deduped[-1].beat) <= 0.01
            and raw_event.pitch_midi == deduped[-1].pitch_midi
        ):
            continue
        deduped.append(raw_event)

    events: list[TrackPitchEvent] = []
    for index, raw_event in enumerate(deduped):
        next_beat = deduped[index + 1].beat if index + 1 < len(deduped) else raw_event.beat + 1
        measure_end_beat = raw_event.measure_index * beats_per_measure + 1
        measure_remaining = max(DOCUMENT_GRID_BEATS, measure_end_beat - raw_event.beat)
        duration_beats = quantize(next_beat - raw_event.beat, DOCUMENT_GRID_BEATS)
        if duration_beats <= 0:
            duration_beats = DOCUMENT_GRID_BEATS
        duration_beats = min(duration_beats, measure_remaining, beats_per_measure)
        events.append(
            event_from_pitch(
                beat=raw_event.beat,
                duration_beats=duration_beats,
                bpm=bpm,
                source="document",
                extraction_method="pdf_vector_document_v1",
                time_signature_numerator=time_signature_numerator,
                time_signature_denominator=time_signature_denominator,
                pitch_midi=raw_event.pitch_midi,
                confidence=raw_event.confidence,
                measure_index=raw_event.measure_index,
                beat_in_measure=raw_event.beat_in_measure,
            )
        )
    return events


def _build_vector_track_diagnostics(
    *,
    slot_id: int,
    raw_events: list[_RawDocumentEvent],
    events: list[TrackPitchEvent],
    document_page_count: int,
    detected_part_count: int,
    source_row_count: int,
    beats_per_measure: float,
) -> dict[str, Any]:
    pitched_events = [
        event
        for event in events
        if not event.is_rest and event.pitch_midi is not None
    ]
    measure_indices = {
        event.measure_index
        for event in events
        if event.measure_index is not None
    }
    page_indices = {raw_event.page_index for raw_event in raw_events}
    range_fit_ratio = _range_fit_ratio(slot_id, pitched_events)
    timing_grid_ratio = _timing_grid_ratio(events)
    avg_event_confidence = (
        sum(event.confidence for event in events) / len(events)
        if events
        else 0
    )
    duration_beats = 0.0
    if events:
        duration_beats = max(event.beat + max(event.duration_beats, 0.25) - 1 for event in events)
    measure_count = len(measure_indices) or max(1, ceil(duration_beats / max(0.25, beats_per_measure)))
    return {
        "engine": "pdf_vector_document_v1",
        "document_page_count": document_page_count,
        "candidate_page_count": len(page_indices),
        "detected_part_count": detected_part_count,
        "source_row_count": source_row_count,
        "event_count": len(events),
        "pitched_event_count": len(pitched_events),
        "measure_count": measure_count,
        "avg_event_confidence": round(avg_event_confidence, 3),
        "range_fit_ratio": round(range_fit_ratio, 3),
        "timing_grid_ratio": round(timing_grid_ratio, 3),
        "density_events_per_measure": round(len(events) / max(1, measure_count), 2),
        "review_hint": _vector_review_hint(
            event_count=len(events),
            range_fit_ratio=range_fit_ratio,
            timing_grid_ratio=timing_grid_ratio,
            detected_part_count=detected_part_count,
        ),
    }


def _range_fit_ratio(slot_id: int, events: list[TrackPitchEvent]) -> float:
    if not events:
        return 0
    low, high = SLOT_PITCH_RANGES.get(slot_id, (0, 127))
    in_range = [
        event
        for event in events
        if event.pitch_midi is not None and low <= event.pitch_midi <= high
    ]
    return len(in_range) / len(events)


def _timing_grid_ratio(events: list[TrackPitchEvent]) -> float:
    if not events:
        return 0
    aligned = 0
    for event in events:
        beat_aligned = abs(event.beat * 4 - round(event.beat * 4)) <= 0.03
        duration_aligned = abs(event.duration_beats * 4 - round(event.duration_beats * 4)) <= 0.03
        if beat_aligned and duration_aligned:
            aligned += 1
    return aligned / len(events)


def _vector_review_hint(
    *,
    event_count: int,
    range_fit_ratio: float,
    timing_grid_ratio: float,
    detected_part_count: int,
) -> str:
    if event_count < 4:
        return "few_events"
    if range_fit_ratio < 0.85:
        return "range_outliers"
    if timing_grid_ratio < 0.82:
        return "rhythm_grid_review"
    if detected_part_count < 4:
        return "partial_document_review"
    return "review_accidentals_and_rhythm"


def _extract_glyphs(page: Any) -> list[_Glyph]:
    glyphs: list[_Glyph] = []
    raw = page.get_text("rawdict")
    for block in raw.get("blocks", []):
        for line in block.get("lines", []):
            for span in line.get("spans", []):
                for char in span.get("chars", []):
                    value = char.get("c", "")
                    bbox = char.get("bbox")
                    if not bbox:
                        continue
                    x0, y0, x1, y1 = bbox
                    glyphs.append(
                        _Glyph(
                            char=value,
                            x=(x0 + x1) / 2,
                            y=(y0 + y1) / 2,
                            x0=x0,
                            y0=y0,
                            x1=x1,
                            y1=y1,
                        )
                    )
    return glyphs


def _key_signature_alterations(
    row: _DocumentRow,
    glyphs: list[_Glyph],
    first_measure_left: float,
) -> dict[str, int]:
    accidentals = [
        glyph
        for glyph in glyphs
        if glyph.char in ACCIDENTAL_OFFSETS
        and row.x0 <= glyph.x <= max(first_measure_left, row.x0 + row.spacing * 8)
        and abs(glyph.y - row.center) <= row.spacing * 5
    ]
    groups = _group_close_values((glyph.x for glyph in accidentals), tolerance=2.0)
    if not groups:
        return {}

    offsets_by_group: list[int] = []
    for group in groups:
        group_chars = [
            glyph.char
            for glyph in accidentals
            if min(group) - 0.1 <= glyph.x <= max(group) + 0.1
        ]
        if not group_chars:
            continue
        offsets = [ACCIDENTAL_OFFSETS[char] for char in group_chars if char in ACCIDENTAL_OFFSETS]
        if offsets:
            offsets_by_group.append(max(set(offsets), key=offsets.count))

    sharp_count = sum(1 for offset in offsets_by_group if offset == 1)
    flat_count = sum(1 for offset in offsets_by_group if offset == -1)
    if sharp_count >= flat_count and sharp_count > 0:
        return {letter: 1 for letter in SHARP_ORDER[: min(sharp_count, len(SHARP_ORDER))]}
    if flat_count > 0:
        return {letter: -1 for letter in FLAT_ORDER[: min(flat_count, len(FLAT_ORDER))]}
    return {}


def _explicit_accidental_for_event(glyph: _Glyph, glyphs: list[_Glyph], row: _DocumentRow) -> int | None:
    candidates = [
        accidental
        for accidental in glyphs
        if accidental.char in ACCIDENTAL_OFFSETS
        and 1 <= glyph.x - accidental.x <= row.spacing * 5
        and abs(glyph.y - accidental.y) <= row.spacing * 1.8
    ]
    if not candidates:
        return None
    candidates.sort(key=lambda item: glyph.x - item.x)
    return ACCIDENTAL_OFFSETS[candidates[0].char]


def _pitch_from_row_y(row: _DocumentRow, y: float) -> tuple[int, str]:
    if row.slot_id == 5:
        bottom_letter = "G"
        bottom_octave = 2
    else:
        bottom_letter = "E"
        bottom_octave = 4
        if row.slot_id in {3, 4}:
            bottom_octave -= 1

    diatonic_step = round((row.bottom - y) / (row.spacing / 2))
    bottom_index = _diatonic_index(bottom_letter, bottom_octave)
    target_index = bottom_index + diatonic_step
    octave, letter_index = divmod(target_index, 7)
    letter = ("C", "D", "E", "F", "G", "A", "B")[letter_index]
    midi = (octave + 1) * 12 + PITCH_CLASS_SEMITONES[letter]
    return midi, letter


def _natural_midi_for_letter(midi: int, letter: str) -> int:
    octave = midi // 12 - 1
    base = (octave + 1) * 12 + PITCH_CLASS_SEMITONES[letter]
    candidates = [base - 12, base, base + 12]
    return min(candidates, key=lambda candidate: abs(candidate - midi))


def _diatonic_index(letter: str, octave: int) -> int:
    return octave * 7 + ("C", "D", "E", "F", "G", "A", "B").index(letter)


def _pitch_in_slot_range(slot_id: int | None, pitch_midi: int) -> bool:
    if slot_id is None:
        return False
    low, high = SLOT_PITCH_RANGES.get(slot_id, (0, 127))
    return low <= pitch_midi <= high


def _slot_id_from_label(text: str) -> int | None:
    normalized = re.sub(r"\s+", " ", text.strip().lower())
    return LABEL_ALIASES.get(normalized)


def _group_close_values(values: Any, *, tolerance: float) -> list[list[float]]:
    groups: list[list[float]] = []
    for value in sorted(float(candidate) for candidate in values):
        if not groups or abs(value - groups[-1][-1]) > tolerance:
            groups.append([value])
        else:
            groups[-1].append(value)
    return groups


def _track_name(slot_id: int) -> str:
    for candidate_slot_id, name in TRACKS:
        if candidate_slot_id == slot_id:
            return name
    return f"Track {slot_id}"
